/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as OpportunityLensRouteImport } from './routes/opportunity-lens'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SavedReportsRouteImport } from './routes/saved-reports'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityLensRoute = OpportunityLensRouteImport.update({
  id: '/opportunity-lens',
  path: '/opportunity-lens',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedReportsRoute = SavedReportsRouteImport.update({
  id: '/saved-reports',
  path: '/saved-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/opportunity-lens': typeof OpportunityLensRoute
  '/processing': typeof ProcessingRoute
  '/report': typeof ReportRoute
  '/research': typeof ResearchRoute
  '/saved-reports': typeof SavedReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/opportunity-lens': typeof OpportunityLensRoute
  '/processing': typeof ProcessingRoute
  '/report': typeof ReportRoute
  '/research': typeof ResearchRoute
  '/saved-reports': typeof SavedReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/opportunity-lens': typeof OpportunityLensRoute
  '/processing': typeof ProcessingRoute
  '/report': typeof ReportRoute
  '/research': typeof ResearchRoute
  '/saved-reports': typeof SavedReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/opportunity-lens'
    | '/processing'
    | '/report'
    | '/research'
    | '/saved-reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/opportunity-lens'
    | '/processing'
    | '/report'
    | '/research'
    | '/saved-reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/opportunity-lens'
    | '/processing'
    | '/report'
    | '/research'
    | '/saved-reports'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  OpportunityLensRoute: typeof OpportunityLensRoute
  ProcessingRoute: typeof ProcessingRoute
  ReportRoute: typeof ReportRoute
  ResearchRoute: typeof ResearchRoute
  SavedReportsRoute: typeof SavedReportsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity-lens': {
      id: '/opportunity-lens'
      path: '/opportunity-lens'
      fullPath: '/opportunity-lens'
      preLoaderRoute: typeof OpportunityLensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-reports': {
      id: '/saved-reports'
      path: '/saved-reports'
      fullPath: '/saved-reports'
      preLoaderRoute: typeof SavedReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  OpportunityLensRoute: OpportunityLensRoute,
  ProcessingRoute: ProcessingRoute,
  ReportRoute: ReportRoute,
  ResearchRoute: ResearchRoute,
  SavedReportsRoute: SavedReportsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
